server.port=${PORT:8080}
server.address=0.0.0.0

# PostgreSQL Configuration - Utilisez les variables d'environnement séparément
spring.datasource.url=${DB_URL}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

# Logging
logging.level.com.abdil=INFO
logging.level.org.springframework.web=WARN

# JWT
jwt.secret=${JWT_SECRET:abdilTaxiSecretKey2024ForJWTTokenGenerationAndValidation}
jwt.expiration=86400000

# Firebase - À commenter temporairement si vous n'avez pas le fichier
# firebase.config.path=firebase/serviceAccountKey.json

# Configuration upload audio
audio.upload.dir=/app/uploads/audio
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
spring.web.resources.static-locations=classpath:/static/,file:/app/uploads/

image.upload.dir=/app/uploads/images

# MeSomb Configuration
mesomb.application.key=${MESOMB_APP_KEY:242ef6fa73d2cac3043ebc731d0b5327357a5153}
mesomb.access.key=${MESOMB_ACCESS_KEY:40bdbf3b-5ae0-4a1e-8301-ec5a725e36bc}
mesomb.secret.key=${MESOMB_SECRET_KEY:88394d28-d6e5-4528-8854-f7447a370038}
mesomb.mode=sandbox
mesomb.currency=XOF
mesomb.language=fr
